name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7247b97ba50697e5dd4abad32cf0d891d4c77c1c5666072fe86e2b8db8b67dc8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
