name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28d98099bc23b2b286095486a404fea150b1eb1496d63573419011f1e86ef72a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
