name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a75a385063a0b9e8f612b147cb936c703f2f3bc80fc7c125d1b1e4207937b968"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
