name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "201f749e5c17a83cd3a53b92c4fd0993c885b1de0dd20451aa73ff1d9ae69149"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
