name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "babae8b43c27a5ba355c60444a391c5a54da8a3d5ecdd5f13bbdf497544694f1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
