name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4c535dd32a57f12353a735f72201b99c560d352e6f2fb20015c783990987263"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
