name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1491fec0f4f83733fbea0cbfc0a72e8dc7751cec0b557f1073cff800a5db9d89"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
