name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "638373e932b259ef3f0eedaaf3d70fc2b34014346af18705b7609e827ab27d88"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
