name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2060d61533cf65f94c74a3d6c9d885c5c0258bf75f183e9c311c6ca3d13763da"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
