name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8fc5adb6ad2ab64097bb2210a6282c31111ee7bd8b08ff4e05372fae730d367"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
