name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4433a6d4319cef1b31e09bec593847306a26644a8d0bc3f2a5ef034cada103ed"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
