name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14232687142f4752e6d48aac2f96ff2c5d421c4a822d23807c914b8f04902b59"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
