name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "402c1058376766e8ec717ab81ce1d0ab800af5da9cadd553379bd93cba43ac26"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
