name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc7afafc0f0e50daf00c925663543f4113f1b858cfb795a9a13f8765202e98b9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
