name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee4f837355ba46785ee84dd723af4604639a0b4b7fae8a875cee75713c9f972e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
