name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab1cb0b97f4cfe0dca0ae7221fc7a9e2310a36c942ace93562ce5845bb7ca100"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
