name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de50afd7e617d635fa9680830a8a53c91093b21ff9b8fdd794ce519511ade696"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
