name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e44b5c396d20af56a5ca53e7448b90e61b599f83cc73c8e647bcffc6ef5dcf91"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
